In [17]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

In [25]:
corpus  = [
    "I want to eat apple",
    "I want to eat banana",
    "Yellow and long banana banana",
    "I like fruit"
]

vector = CountVectorizer()

In [26]:
def cos_sim(A,B):
    return dot(A,B)/(norm(A)*norm(B))

In [27]:
dtm = vector.fit_transform(corpus).toarray()
print(dtm)

[[0 1 0 1 0 0 0 1 1 0]
 [0 0 1 1 0 0 0 1 1 0]
 [1 0 2 0 0 0 1 0 0 1]
 [0 0 0 0 1 1 0 0 0 0]]


In [28]:
ndtm=np.array(dtm)

In [29]:
print("文書1と2の間の類似度: ",cos_sim(ndtm[0],ndtm[1]))
print("文書2と3の間の類似度: ",cos_sim(ndtm[1],ndtm[2]))
print("文書3と4の間の類似度: ",cos_sim(ndtm[2],ndtm[3]))
print("文書1と3の間の類似度: ",cos_sim(ndtm[0],ndtm[2]))

文書1と2の間の類似度:  0.75
文書2と3の間の類似度:  0.3779644730092272
文書3と4の間の類似度:  0.0
文書1と3の間の類似度:  0.0


In [30]:
doc1 = np.array([0,1,1,1])
doc2 = np.array([1,0,1,1])
doc3 = np.array([2,0,2,2])

In [31]:
print("文書1と2の間の類似度: ",cos_sim(doc1, doc2))
print("文書2と3の間の類似度: ",cos_sim(doc2, doc3))
print("文書3と4の間の類似度: ",cos_sim(doc1, doc3))

文書1と2の間の類似度:  0.6666666666666667
文書2と3の間の類似度:  1.0000000000000002
文書3と4の間の類似度:  0.6666666666666667
