In [1]:
#Embedding(vocab_size, output_dim, input_length=input_length)

In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences 

In [3]:
sentences = ['nice great best amazing', 'stop lies', 'pitiful nerd', 'excellent work', 'supreme quality', 'bad', 'highly respectable']
y_train = [1, 0, 0, 1, 1, 0, 1] #positive: 1  Negative: 0

In [4]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(sentences)
vocab_size = len(tokenizer.word_index) + 1
print("vocab size: ",vocab_size)

vocab size:  16


In [5]:
X_encoded = tokenizer.texts_to_sequences(sentences)
print("Integer Encoding : ",X_encoded)

Integer Encoding :  [[1, 2, 3, 4], [5, 6], [7, 8], [9, 10], [11, 12], [13], [14, 15]]


In [6]:
max_len = max(len(l) for l in X_encoded)
print("Maximum length: ",max_len)

Maximum length:  4


In [10]:
X_train = pad_sequences(X_encoded, maxlen=max_len, padding='post')
y_train = np.array(y_train)
print("Padded train_X data: ")
print(X_train)
print(X_train.shape)

Padded train_X data: 
[[ 1  2  3  4]
 [ 5  6  0  0]
 [ 7  8  0  0]
 [ 9 10  0  0]
 [11 12  0  0]
 [13  0  0  0]
 [14 15  0  0]]
(7, 4)


In [9]:
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Embedding, Flatten, Input

In [28]:
embedding_dim = 4

inputs = Input(shape=(4))
model = Embedding(vocab_size, embedding_dim, input_length = max_len)(inputs)
model = Flatten()(model)
output = Dense(1, activation = 'sigmoid')(model)
model = Model(inputs=inputs, outputs=output)

In [29]:
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['acc'])
model.fit(X_train, y_train, epochs=100, verbose=2)

Epoch 1/100
1/1 - 3s - loss: 0.6894 - acc: 0.4286 - 3s/epoch - 3s/step
Epoch 2/100
1/1 - 0s - loss: 0.6879 - acc: 0.4286 - 8ms/epoch - 8ms/step
Epoch 3/100
1/1 - 0s - loss: 0.6863 - acc: 0.4286 - 10ms/epoch - 10ms/step
Epoch 4/100
1/1 - 0s - loss: 0.6848 - acc: 0.4286 - 8ms/epoch - 8ms/step
Epoch 5/100
1/1 - 0s - loss: 0.6833 - acc: 0.5714 - 7ms/epoch - 7ms/step
Epoch 6/100
1/1 - 0s - loss: 0.6818 - acc: 0.8571 - 14ms/epoch - 14ms/step
Epoch 7/100
1/1 - 0s - loss: 0.6802 - acc: 0.8571 - 15ms/epoch - 15ms/step
Epoch 8/100
1/1 - 0s - loss: 0.6787 - acc: 1.0000 - 12ms/epoch - 12ms/step
Epoch 9/100
1/1 - 0s - loss: 0.6772 - acc: 1.0000 - 15ms/epoch - 15ms/step
Epoch 10/100
1/1 - 0s - loss: 0.6757 - acc: 1.0000 - 9ms/epoch - 9ms/step
Epoch 11/100
1/1 - 0s - loss: 0.6741 - acc: 1.0000 - 12ms/epoch - 12ms/step
Epoch 12/100
1/1 - 0s - loss: 0.6726 - acc: 1.0000 - 13ms/epoch - 13ms/step
Epoch 13/100
1/1 - 0s - loss: 0.6710 - acc: 1.0000 - 14ms/epoch - 14ms/step
Epoch 14/100
1/1 - 0s - loss: 0.6

In [32]:
print(tokenizer.word_index.items())

dict_items([('nice', 1), ('great', 2), ('best', 3), ('amazing', 4), ('stop', 5), ('lies', 6), ('pitiful', 7), ('nerd', 8), ('excellent', 9), ('work', 10), ('supreme', 11), ('quality', 12), ('bad', 13), ('highly', 14), ('respectable', 15)])


In [39]:
model.predict(sentences)

ValueError: in user code:

    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 2041, in predict_function  *
        return step_function(self, iterator)
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 2027, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 2015, in run_step  **
        outputs = model.predict_step(data)
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\training.py", line 1983, in predict_step
        return self(x, training=False)
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\utils\traceback_utils.py", line 70, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\ProgramData\Anaconda3\lib\site-packages\keras\engine\input_spec.py", line 277, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer "model_4" "                 f"(type Functional).
    
    Input 0 of layer "dense_4" is incompatible with the layer: expected axis -1 of input shape to have value 16, but received input with shape (None, 4)
    
    Call arguments received by layer "model_4" "                 f"(type Functional):
      • inputs=tf.Tensor(shape=(None,), dtype=string)
      • training=False
      • mask=None
