In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer

In [6]:
texts = ['I want to eat a banana.','eat a banana banana.','Long and yellow banana.','I like fruits.']

In [7]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
print(tokenizer.word_index)

{'banana': 1, 'i': 2, 'eat': 3, 'a': 4, 'want': 5, 'to': 6, 'long': 7, 'and': 8, 'yellow': 9, 'like': 10, 'fruits': 11}


In [8]:
print(tokenizer.texts_to_matrix(texts, mode = 'count')) #count -> DTM

[[0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 2. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1.]]


In [9]:
print(tokenizer.texts_to_matrix(texts, mode = 'binary')) #binary

[[0. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 1. 1.]]


In [10]:
print(tokenizer.texts_to_matrix(texts, mode = 'tfidf').round(2)) #TF-IDF  round off .2

[[0.   0.69 0.85 0.85 0.85 1.1  1.1  0.   0.   0.   0.   0.  ]
 [0.   1.17 0.   0.85 0.85 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.69 0.   0.   0.   0.   0.   1.1  1.1  1.1  0.   0.  ]
 [0.   0.   0.85 0.   0.   0.   0.   0.   0.   0.   1.1  1.1 ]]


In [11]:
print(tokenizer.texts_to_matrix(texts, mode = 'freq').round(2)) #frequency for each sentence

[[0.   0.17 0.17 0.17 0.17 0.17 0.17 0.   0.   0.   0.   0.  ]
 [0.   0.5  0.   0.25 0.25 0.   0.   0.   0.   0.   0.   0.  ]
 [0.   0.25 0.   0.   0.   0.   0.   0.25 0.25 0.25 0.   0.  ]
 [0.   0.   0.33 0.   0.   0.   0.   0.   0.   0.   0.33 0.33]]
