In [25]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM, Bidirectional, GRU

In [26]:
train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
print(np.shape(train_X)) #1, lenth of sentence (timesteps), vocab dimention
print(train_X)

(1, 4, 5)
[[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]


In [27]:
train_X = np.array(train_X,dtype=np.float32)

In [28]:
rnn = SimpleRNN(3, return_sequences=False, return_state=False)
hidden_state = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))

hidden state : [[0.98321766 0.58797216 0.6851658 ]], shape: (1, 3)


In [29]:
rnn = SimpleRNN(3, return_sequences=True, return_state=False)
hidden_state = rnn(train_X)

print('hidden state : {}, shape: {}'.format(hidden_state, hidden_state.shape))

hidden state : [[[-0.9466328   0.97181004 -0.9977614 ]
  [-0.99152106  0.9740493  -0.99801266]
  [-0.9979192   0.9477412  -0.9969004 ]
  [-0.9892109   0.9441146  -0.99930745]]], shape: (1, 4, 3)


In [30]:
rnn = SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states, last_state = rnn(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_state, last_state.shape))

hidden states : [[[ 0.6130221  -0.9559332   0.99901587]
  [-0.82862073 -0.99411136  0.9253961 ]
  [-0.4846016  -0.9983197   0.7063365 ]
  [ 0.66786695 -0.9985984  -0.46974307]]], shape: (1, 4, 3)
last hidden state : [[ 0.66786695 -0.9985984  -0.46974307]], shape: (1, 3)


In [31]:
lstm = LSTM(3, return_sequences=False, return_state=True)
hidden_states, last_hidden_state, last_cell_state = lstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_hidden_state, last_hidden_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

hidden states : [[ 0.06018003 -0.400327    0.3564455 ]], shape: (1, 3)
last hidden state : [[ 0.06018003 -0.400327    0.3564455 ]], shape: (1, 3)
last cell state : [[ 0.10660806 -0.60605013  0.85902303]], shape: (1, 3)


In [32]:
lstm = LSTM(3, return_sequences=True, return_state=True)
hidden_states, last_hidden_state, last_cell_state = lstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_hidden_state, last_hidden_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

hidden states : [[[ 0.4397436  -0.06700115 -0.6173528 ]
  [ 0.5465901  -0.1055913  -0.60148424]
  [ 0.64823353 -0.12049786 -0.5054307 ]
  [ 0.6168994  -0.3066118  -0.608404  ]]], shape: (1, 4, 3)
last hidden state : [[ 0.6168994 -0.3066118 -0.608404 ]], shape: (1, 3)
last cell state : [[ 1.3292944 -0.8545365 -1.9241016]], shape: (1, 3)


In [33]:
k_init = tf.keras.initializers.Constant(value=0.1)
b_init = tf.keras.initializers.Constant(value=0)
r_init = tf.keras.initializers.Constant(value=0.1)

In [34]:
bilstm = Bidirectional(LSTM(3, return_sequences=False, return_state=True, \
                            kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states : [[0.6303139  0.6303139  0.6303139  0.70387346 0.70387346 0.70387346]], shape: (1, 6)
forward state : [[0.6303139 0.6303139 0.6303139]], shape: (1, 3)
backward state : [[0.70387346 0.70387346 0.70387346]], shape: (1, 3)


In [35]:
bilstm = Bidirectional(LSTM(3, return_sequences=True, return_state=True, \
                            kernel_initializer=k_init, bias_initializer=b_init, recurrent_initializer=r_init))
hidden_states, forward_h, forward_c, backward_h, backward_c = bilstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('forward state : {}, shape: {}'.format(forward_h, forward_h.shape))
print('backward state : {}, shape: {}'.format(backward_h, backward_h.shape))

hidden states : [[[0.35906476 0.35906476 0.35906476 0.70387346 0.70387346 0.70387346]
  [0.5511133  0.5511133  0.5511133  0.5886358  0.5886358  0.5886358 ]
  [0.5911575  0.5911575  0.5911575  0.39516988 0.39516988 0.39516988]
  [0.6303139  0.6303139  0.6303139  0.2194224  0.2194224  0.2194224 ]]], shape: (1, 4, 6)
forward state : [[0.6303139 0.6303139 0.6303139]], shape: (1, 3)
backward state : [[0.70387346 0.70387346 0.70387346]], shape: (1, 3)


In [36]:
gru = GRU(3, return_sequences=False, return_state=True)
hidden_states, last_hidden_state, last_cell_state = lstm(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states, hidden_states.shape))
print('last hidden state : {}, shape: {}'.format(last_hidden_state, last_hidden_state.shape))
print('last cell state : {}, shape: {}'.format(last_cell_state, last_cell_state.shape))

hidden states : [[[ 0.4397436  -0.06700115 -0.6173528 ]
  [ 0.5465901  -0.1055913  -0.60148424]
  [ 0.64823353 -0.12049786 -0.5054307 ]
  [ 0.6168994  -0.3066118  -0.608404  ]]], shape: (1, 4, 3)
last hidden state : [[ 0.6168994 -0.3066118 -0.608404 ]], shape: (1, 3)
last cell state : [[ 1.3292944 -0.8545365 -1.9241016]], shape: (1, 3)
