In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
X, y = zip(['a',1],['b',2],['c',3])
print("X's data : ",X)
print("y's data : ",y)

X's data :  ('a', 'b', 'c')
y's data :  (1, 2, 3)


In [6]:
values = [['HappyOtterScripts AudioSyncR',1],
         ['Plz check your schedule',0],
         ['Hello! It\'s been a long time',0],
         ['24Hr Flash Sale: TickStrike Lifetime',1]]
columns = ['Text of mail', 'Spam or not']

df = pd.DataFrame(values, columns=columns)
df

Text of mail  Spam or not
0          HappyOtterScripts AudioSyncR            1
1               Plz check your schedule            0
2          Hello! It's been a long time            0
3  24Hr Flash Sale: TickStrike Lifetime            1

In [7]:
X = df['Text of mail']
y = df['Spam or not']

In [8]:
print('X\'s data :',X.to_list())
print('y\'s data :',y.to_list())

X's data : ['HappyOtterScripts AudioSyncR', 'Plz check your schedule', "Hello! It's been a long time", '24Hr Flash Sale: TickStrike Lifetime']
y's data : [1, 0, 0, 1]


In [10]:
np_array = np.arange(0,16).reshape((4,4))
print("All data : \n",np_array)

All data : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [22]:
X = np_array[:, :3]
y = np_array[:,3]

print('X\'s data :')
print(X)
print('y\'s data :',y)

X's data :
[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
y's data : [ 3  7 11 15]


In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=1234)

In [30]:
X, y = np.arange(10).reshape((5, 2)), range(5)

print('X\'s data :')
print(X)
print('y\'s data :',list(y))

X's data :
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
y's data : [0, 1, 2, 3, 4]


In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1234)

In [27]:
print('X\'s train data :\n',X_train)
print('X\'s test data :\n',X_test)

X's train data :
 [[2 3]
 [4 5]
 [6 7]]
X's test data :
 [[8 9]
 [0 1]]


In [31]:
print('y\'s train data :\n',y_train)
print('y\'s test data :\n',y_test)

y's train data :
 [1, 2, 3]
y's test data :
 [4, 0]


In [45]:
X, y = np.arange(0,24).reshape((12,2)), range(12)

print('X\'s data :\n',X)
print('y\'s data :\n',list(y))

X's data :
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
y's data :
 [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [46]:
num_of_train = int(len(X) * 0.8)
num_of_test = int(len(X) - num_of_train)
print('Size of the train data :', num_of_train)
print('Size of the test data :', num_of_test)

Size of the train data : 9
Size of the test data : 3


In [47]:
X_test = X[num_of_train:]
y_test = y[num_of_train:]
X_train = X[:num_of_train]
y_train = y[:num_of_train]

In [49]:
print('X\'s test data :\n',X_test)
print('y\'s test data :\n',list(y_test))

X's test data :
 [[18 19]
 [20 21]
 [22 23]]
y's test data :
 [9, 10, 11]
