In [1]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

In [6]:
text = """He is sick\n
That is so sick\n
The sick cat is dying\n"""

In [7]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
vocab_size = len(tokenizer.word_index) + 1
print("Size of vocabulary : %d" % vocab_size)

Size of vocabulary : 9


In [8]:
print(tokenizer.word_index)

{'is': 1, 'sick': 2, 'he': 3, 'that': 4, 'so': 5, 'the': 6, 'cat': 7, 'dying': 8}


In [25]:
sequences = list()
for line in text.split('\n'):
    encoded = tokenizer.texts_to_sequences({line})[0]
    #print(encoded)
    for i in range(1, len(encoded)):
        sequence = encoded[:i+1]
        sequences.append(sequence)

In [28]:
print(sequences,"\nCount of sample : ",len(sequences))

[[3, 1], [3, 1, 2], [4, 1], [4, 1, 5], [4, 1, 5, 2], [6, 2], [6, 2, 7], [6, 2, 7, 1], [6, 2, 7, 1, 8]] 
Count of sample :  9


In [29]:
max_len = max(len(l) for l in sequences)
print("Maximum length of sample : {}".format(max_len))

Maximum length of sample : 5


In [30]:
sequences = pad_sequences(sequences, maxlen=max_len, padding='pre')

In [31]:
print(sequences)

[[0 0 0 3 1]
 [0 0 3 1 2]
 [0 0 0 4 1]
 [0 0 4 1 5]
 [0 4 1 5 2]
 [0 0 0 6 2]
 [0 0 6 2 7]
 [0 6 2 7 1]
 [6 2 7 1 8]]
